version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
#    networks:
#      - k6

#  warehouse:
#    image: szalaigeri/warehouse:1.0.0
#    restart: on-failure
#    networks:
#      - k6
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres
#    environment:
#      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/warehouse
#
#  influxdb:
#    image: influxdb:1.8
#    #    entrypoint: /bin/sh
#    #    user: root
#    networks:
#      - k6
#    ports:
#      - "8086:8086"
#    environment:
#      - INFLUXDB_DB=k6
#    depends_on:
#      - warehouse
#
#  k6:
#    image: loadimpact/k6:latest
#    networks:
#      - k6
#    ports:
#      - "6565:6565"
#    environment:
#      - K6_OUT=influxdb=http://influxdb:8086/k6
#    volumes:
#      - ../src/test/k6:/scripts
#    command: run /scripts/first_uc.js
#    depends_on:
#      - influxdb

#networks:
#  k6: