version: '3.8'

services:

  order-service:
    image: szalaigeri/order-service:1.0.0
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - warehouse
    environment:
      - WAREHOUSE_URL=warehouse

  warehouse:
    image: szalaigeri/warehouse:1.0.0
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    name: backend