server:
  port: 8080

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/order-service}
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
    enabled: ${DATASOURCE_ENABLED:true}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

warehouse:
  host: ${WAREHOUSE_URL:localhost}
  base-url: http://${warehouse.host}:8081/api/v1/warehouse
  order-foods-url: http://${warehouse.host}:8081/api/v1/warehouse/foods/order
  check-foods-url: http://${warehouse.host}:8081/api/v1/warehouse/foods/check

logging:
  enabled: ${LOGGING_ENABLED:false}
