apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-volume-wh
  labels:
    type: local
spec:
  #we use local node storage here!
  #kubectl get storageclass
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-claim-wh
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-wh
  labels:
    app: postgres-wh
data:
  POSTGRES_DB: warehouse
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-wh
spec:
  serviceName: postgres-wh
  selector:
    matchLabels:
      app: postgres-wh
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-wh
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: example-claim-wh
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-wh
  labels:
    app: postgres-wh
spec:
  selector:
    app: postgres-wh
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432