version: '3.8'

services:

  postgres-order-service:
    container_name: postgres-order-service
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-service
    ports:
      - "5433:5432"